# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Coffee-Editor

on: [pull_request]
  #workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Run on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup node 10
      uses: actions/setup-node@v2
      with:
        node-version: 10
    - name: Build Java Maven
      run: | 
        cd backend/releng/org.eclipse.emfcloud.coffee.parent
        mvn clean install
    - name: Build Npm
      run: | 
        cd web
        yarn
